import type { Metadata } from "next";
import "./globals.css";
import { BrowserRouter } from "react-router-dom";

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,management
}: Readonly<{
  children: React.ReactNode,management:React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>{children}</div>
        <div>{management}</div>
      </body>
    </html>
  );
}
